version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: password
      POSTGRES_DATABASE: projects-api-development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command:
      bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_NAME: projects-api-development
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    volumes:
      - .:/projects-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db