version: "2.1"
services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command:
      bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    volumes:
      - .:/projects-api
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy